### ISSUE TITLE
replacement Types

### ISSUE THREAD

**Issue by warrenc5** [floverfelt/find-and-replace-maven-plugin#1]
Firstly thanks for the plugin - I'm using it to replace javax with jaxarta on the raml to maven plugin for a small personal summer project.

It's non obvious which are the possibilities for replacementType - I've grokked the codebase so I worked it out but for the noobs it would be good to spell it out. :) 

Peace.

**Comment by floverfelt** [comment]
Glad to hear you're getting some use out of this! :)

I've updated the README with a comment that calls this out explicitly: https://github.com/floverfelt/find-and-replace-maven-plugin/pull/2

Also, for anybody who stumbles on this later, the doc site calls this out as well, though admittedly it can be tricky to find: https://floverfelt.org/find-and-replace-maven-plugin/find-and-replace-mojo.html
