### ISSUE TITLE
Drop commons-lang3 usage or define the dependency - maven 3.9.8 requirement

### ISSUE THREAD

**Issue by hazendaz** [floverfelt/find-and-replace-maven-plugin#13]
As of maven 3.9.8, it no longer has any commons-lang3 in it.  No usage was supposed to be picking that up with direct usage without defining.  Maven did warn in the change logs.  This project is therefore affected.  A fork that seems now to be trying to move forwards appears to have already fixed.  Not sure if the fork is the go forwards or not as prior issues raised haven't been addressed either so the plugin is in need of some love :)

**Comment by floverfelt** [comment]
I dropped the commons-lang3 references altogether, it should no longer require that lib at all.

The newly released artifact should show up in maven repository/search soon: https://central.sonatype.com/artifact/io.github.floverfelt/find-and-replace-maven-plugin/versions

Let me know if you see any other issues.
