### ISSUE TITLE
how to use this with maven-shade-plugin

### ISSUE THREAD

**Issue by sify21** [floverfelt/find-and-replace-maven-plugin#14]
I want to replace relocated class names in the file `META-INF/sisu/javax.inject.Named`, which exists in the shaded jar, is that possible?

**Comment by floverfelt** [comment]
I don't think you'd want to use this plugin for that, I'd recommend looking into the advanced configuration of the shade plugin, it seems to have your use case described here: https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html

Or, use/write your own resource transformer: https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html
