### ISSUE TITLE
Wrong version in latest release

### ISSUE THREAD

**Issue by arburk** [floverfelt/find-and-replace-maven-plugin#5]
Hi @floverfelt 

Thank you so much for your quick reply and accepting/merging PR and subsequent release. Unfortunately the version in POM of the latter seems to be wrong (still 1.0-SNAPSHOT). Thus its usage is not working due to following error:
```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:40 min
[INFO] Finished at: 2022-03-09T07:30:15+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Invalid plugin descriptor for io.github.floverfelt:find-and-replace-maven-plugin:1.1 (C:\dev\maven\repo\io\github\floverfelt\find-and-replace-maven-plugin\1.1\find-and-replace-maven-plugin-1.1.jar), Plugin's descriptor contains the wrong version: 1.0-SNAPSHOT -> [Help 1]
```

May I ask you to provide another release with fixed version info. And while doing so, you might also add the new parameter to ***readme.md***?

Thank you and best regards
Arno

**Comment by floverfelt** [comment]
The new release is 1.1.0, not 1.1, I appended the additional version in case of any minor bugfixes to the encoding work, I'll update the README later today.
