### ISSUE TITLE
Please fix scope of maven plugin api to provided per maven requirements

### ISSUE THREAD

**Issue by hazendaz** [floverfelt/find-and-replace-maven-plugin#8]
currently this is in compile scope which goes against maven guidelines and just serves to bloat m2 repo.  Please build with maven 3.9.2 to see the issue.  It needs to be fixed so it reduces bloat.  Most major plugins are already done with this.

**Comment by floverfelt** [comment]
Thanks, I see the issue now. This plugin needs a slew of build improvements and I will add this.

**Comment by floverfelt** [comment]
Fixed in #11
